baseURL = "/"
languageCode = "en-us"
title = "Diógenes Polanco"
rssLimit = 20
copyright = "2022 Janne Kemppainen All rights reserved"
minify = false

[Author]
  name = "diogenespolanco"
  email = "diogenespolancomartinez@gmail.com"

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["html", "json", "rss"]
