title: the key is knowledge
baseURL: /
params:
  layout_style: overflow
  palette: blue
  header:
    title: Diogenes Polanco
    tagline: '\Develop?Enjoy=Contribute'
    profile_img: >-
      https://avatars.githubusercontent.com/u/2844235?v=4
    bg: dark
    has_nav: true
    has_social: true
  footer:
    content: '&copy; All rights reserved.'
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
