title: the key is knowledge
baseURL: /
params:
  layout_style: overflow
  palette: blue
  header:
    title: Diogenes Polanco
    tagline: '\Develop?Enjoy=Contribute'
    profile_img: >-
      https://res.cloudinary.com/practicaldev/image/fetch/s--pNOaTCUp--/c_fill,f_auto,fl_progressive,h_320,q_auto,w_320/https://thepracticaldev.s3.amazonaws.com/uploads/user/profile_image/247106/5c938fc9-ab00-49cb-8bdf-3f904b9d954b.jpeg
    bg: dark
    has_nav: true
    has_social: true
  footer:
    content: '&copy; All rights reserved.'
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
